"""alteration of some table columns to harmonize with th CLI

Revision ID: 0021e2c034ed
Revises: c3dc159bd643
Create Date: 2025-05-29 07:42:38.286249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0021e2c034ed'
down_revision: Union[str, None] = 'c3dc159bd643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'credits')
    # ### end Alembic commands ###
