"""creating Enrollment table

Revision ID: 495cff1c84ac
Revises: f20c764e54d5
Create Date: 2025-05-27 17:35:40.649499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495cff1c84ac'
down_revision: Union[str, None] = 'f20c764e54d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('semester', sa.String(length=50), nullable=True))
    op.drop_column('courses', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('title', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('courses', 'semester')
    op.drop_column('courses', 'name')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
